//
//  ShopItems.swift
//  onepageaday
//
//  Created by 이창현 on 2021/01/01.
//

import Foundation

class ShopItems {
    let shopItems = [ShopItem(title: "매일력",
                              detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.", price: 0,
                              questions: ["눈을 감으면 무슨 생각이 나나요?",
                                "혼자 있으면 무얼 하나요?",
                                "오늘 점심으로 무엇을 먹었나요?",
                                "오늘 날씨는 어떤가요?",
                                "잠이 오지 않을 때 어떻게 하나요?",
                                "쉬는 날 무엇을 하고 싶은가요?",
                                "한 가지 소원을 들어준다면 무엇을 하고 싶어요?",
                                "나를 한 문장으로 소개한다면?",
                                "지금 하늘은 무슨 색인가요?",
                                "지금 어디든 갈 수 있다면, 어디에 가고 싶나요?",
                                "좋아하는 음식이 무엇인가요?",
                                "지금 보고 싶은 사람이 있나요?",
                                "어떤 색을 좋아하나요?",
                                "가장 좋았던 여행은 어디였나요?",
                                "어떤 계절이 가장 싫은가요?",
                                "가장 좋아하는 채소는 무엇인가요?",
                                "친구들의 이름을 적어보세요.",
                                "가장 고마운 사람은 누구인가요?",
                                "어떤 노래를 좋아하나요?",
                                "가장 좋아하는 운동은 무엇인가요?",
                                "어떤 악기를 좋아하나요?",
                                "가장 기억나는 장소는 어디인가요?",
                                "가장 좋아하는 숫자는 무엇인가요?",
                                "가장 갖고 싶은 물건은 무엇인가요?",
                                "요즘 가장 재밌는 것이 무엇인가요?",
                                "오늘 꼭 하고 싶은 일이 무언가요?",
                                "무얼 할 때 시간이 빠르게 가나요?",
                                "최근 가장 즐거웠던 일은 무엇인가요?",
                                "최근 가장 고민되는 것은 무엇인가요?",
                                "내가 가장 좋아하는 것은 무엇인가요?"],
                              additionalImageLinks: ["https://previews.123rf.com/images/dafnadar/dafnadar1707/dafnadar170700015/82894770-handsome-young-adult-men-in-shirt-and-trousers-hand-drawing-illustration-with-black-line-art-man-wit.jpg","https://psycatgames.com/ko/magazine/conversation-starters/250-questions-to-ask-a-guy/feature-image_hu4a7c8397bd008fb23013e84fd92f05ba_1338079_1920x1080_fill_q75_box_center.jpg"], bookImage: "https://www.foodbank.co.kr/news/photo/201803/54389_10478_1953.jpg", privateMode: false, hashtags: ["매일력","매일매일"]),

                     ShopItem(title: "사물력", detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.", price: 0, questions: [
                        "아침에 눈을 떴을 때 혹은 하루를 마칠 때 기록을 남기나요?",
                        "책상과 침대 중 어디에서 시간을 더 오래 보내나요?",
                        "일을 마치고 집에 돌아오면 어떤 옷을 입고 있나요?",
                        "책상 위에 무엇이 놓여 있나요?",
                        "요즘 주로 입는 옷은 무슨 색인가요?",
                        "운동할 땐 주로 무엇을 입나요?",
                        "가장 좋아하는 구두는 무슨 색인가요?",
                        "캠핑을 가본 적이 있나요?",
                        "집에서 운동을 하나요?",
                        "냉장고가 꽉 차 있나요? 아니면 빈 공간이 많나요?",
                        "어떤 커피를 좋아하나요? 또는 커피를 어떻게 내려마시나요?",
                        "옷을 많이 가지고 있다고 생각하나요?",
                        "책을 몇 권 가지고 있나요?",
                        "함께 하는 식물이 있나요?",
                        "운동할 때만 신는 신발이 따로 있나요?",
                        "매일 쓰는 수건은 무슨 색인가요?",
                        "아끼는 컵이 있나요?",
                        "우산은 어떤 색깔 어떤 크기를 가지고 있나요?",
                        "얼굴을 닦고 나서 무엇을 바르나요?",
                        "집에 있을 때는 어떤 옷을 입고 있나요?",
                        "평상시에 어떤 가방을 들고 다니나요?",
                        "일주일에 몇 번 세탁하나요?",
                        "세탁 전에 옷은 어디에 모아두나요?",
                        "시계를 가지고 있나요?",
                        "매일 몸무게를 재나요?",
                        "평소에 텀블러를 가지고 다니나요?",
                        "필름 카메라를 사용해 본적이 있나요?",
                        "스마트폰을 하루에 얼마나 사용하나요?",
                        "무선 이어폰과 유선 이어폰 중 무엇을 선호하나요?",
                        "요리를 직접 하는 것을 좋아하나요?"
                              ], additionalImageLinks: ["https://i.pinimg.com/564x/2f/d7/8e/2fd78e90c645537e3089306b79aa509b.jpg"], bookImage: "https://t1.daumcdn.net/blogfile/fs11/26_blog_2008_09_02_11_11_48bca0d589167?x-content-disposition=inline&filename=t1.jpg", privateMode: true, hashtags: ["사물력","사물사물"]),
                     
                     
                     ShopItem(title: "어떤집",
                              detail: "50가지 질문입니다.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales, magna vitae convallis bibendum, purus turpis faucibus quam, a feugiat orci ante eget tortor. Maecenas magna dolor, tempus ac odio consequat, placerat elementum purus. Donec nec enim dui. Praesent elementum tempor urna eu volutpat. Cras venenatis tortor at dui imperdiet, ornare tincidunt est imperdiet. Integer tempor risus non dolor hendrerit elementum. Nulla egestas metus et vehicula iaculis. Vivamus at diam non libero cursus tempus. In hac habitasse platea dictumst. Morbi ex sapien, sagittis nec est in, tincidunt malesuada eros. Nulla volutpat nisl eros, in pretium arcu posuere eget. Sed nec urna eget metus ultrices varius.",
                              price: 0,
                              questions: [
                        "친한 손님이 오면 자고 가도 되나요?",
                                "집에 들어서면 무엇이 가장 먼저 보였으면 하나요?",
                                "식물 기르는 것을 좋아하나요?",
                                "계절별로 좋아하는 꽃이 있나요?",
                                "깻잎, 파, 고추를 심어본 적 있나요?",
                                "집에 하늘을 바라볼  수 있는 공간이 있었으면 하나요?",
                                "집 근처에 어떤 곳이 있으면 좋을까요?",
                                "내 차를 갖고 싶은가요?",
                                "소파에서 주로 무엇을 하나요?",
                                "함께 밥을 먹으며 이야기 나눌 사람이 있나요?",
                                "옷 정리하는 것을 좋아하나요?",
                                "평소 애정을 갖고 수집하는 물건이 있나요?",
                                "책상에서 주로 무엇을 하나요?",
                                "바닥에 앉아서 누군가와 차를 마신 적이 있나요?",
                                "자주 바라보고 싶은 물건이 있나요?",
                                "큰 거울이 있다면 어디에 놓고 싶나요?",
                                "화장은 어디에서 하나요?",
                                "내 방을 가기 위해 어디를 지나쳐야 하나요?",
                                "소음에 대해 민감한 편인가요?",
                                "집에 있는 물건들은 어떻게 정리하고 보관하나요?",
                                "집안의 밝기와 분위기가 어땠으면 좋겠나요?",
                                "내 방에 햇빛이 가득 들어오는 시간을 아나요?",
                                "방에서 자연스러운 바람을 느껴본 적 있나요?",
                                "목욕하는 것을 좋아하나요?",
                                "집에 둘이 마주 보고 앉아서 이야기 나눌 수 있는 공간이 있나요?",
                                "집의 무엇을 보면 기분이 좋아지나요?",
                                "집의 무엇을 생각하면 미소가 지어지나요?",
                                "집안에 추억을 담아두는 공간이 있나요?",
                                "집에 혼자만 조용히 있을 수 있는 공간이 있나요?",
                                "집에 가고 싶을 때 가장 먼저 떠오르는 곳이 있나요? ",
                     
                     ],
                     additionalImageLinks: ["https://contents.sixshop.com/uploadedFiles/16736/product/image_1580274048321.jpg"],
                     bookImage: "https://image.ajunews.com/content/image/2020/08/29/20200829141039628211.jpg", privateMode: false, hashtags: ["무료","집집"])
                              ]
    
}
